name:                server
version:             0.1.0.0
github:              "SlimTim10/server"
license:             MIT
author:              "SlimTim10"
maintainer:          "slimtim10@gmail.com"
copyright:           "SlimTim10"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            none

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SlimTim10/server#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.4.6.0 && < 1.5
- bytestring >= 0.10.10.0 && < 0.11
- binary >= 0.8.6.0 && < 0.9
- serialport >= 0.4.7 && < 0.5
- optparse-applicative >= 0.15.0.0 && < 0.16
- split >= 0.2.3.4 && < 0.3
- containers >= 0.6.2.1 && < 0.7
- mtl >= 2.2 && < 2.3
- time >= 1.8 && < 1.10
- yaml >= 0.11.1.0 && < 0.12
- unordered-containers >= 0.2.8.0 && < 0.3
- text >= 1.2.3.0 && < 1.3
- scientific >= 0.3.6.2 && < 0.4

library:
  source-dirs: src

executables:
  server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - server

tests:
  server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - server
    - hspec

default-extensions:
  - OverloadedStrings
  - DeriveGeneric
  - DeriveAnyClass
  - DuplicateRecordFields
  - NamedFieldPuns
